ci: adding Java package name check (#9172)
In past, we published Java classes with wrong package names due to improper java_package field in proto files (https://protobuf.dev/programming-guides/proto3/#options). This check excludes these existing files:

- `cloud-build.*v2`
- `google/monitoring/v3/DroppedLabelsOuterClass.java`
- `google/cloud/policytroubleshooter/v1/Explanations.java`

diff --git a/.github/workflows/generated_files_sync.yaml b/.github/workflows/generated_files_sync.yaml
--- a/.github/workflows/generated_files_sync.yaml
+++ b/.github/workflows/generated_files_sync.yaml
@@ -144,3 +144,38 @@ jobs:
           echo "Passed ${POM}"
         done
         echo "All group IDs start with com.google.maps. Good."
+
+  package_name_check:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v3
+    - name: Ensure no new invalid package name in Java files
+      shell: bash
+      run: |
+        # grep returns "1" (error) when no output
+        set +e
+        echo "Finding files matching '*main/java/google/*.java'"
+        # In past, we published Java classes with wrong package names (google.)
+        # due to improper java_package field in proto files (https://protobuf.dev/programming-guides/proto3/#options).
+        # This check excludes these existing files.
+        
+        # java/com/google : This is the standard package
+        # samples         : Samples are not shipped as a library
+        # grafeas         : java-grafeas is known to have special package name
+        # cloud-build v2  : java_package was not configured when we published
+        #                   the Cloud Build V2 client library
+        # the rest        : the same as above
+        invalid_files=$(find . -name '*.java' \
+            |grep --invert-match 'java/com/google' \
+            |grep --invert-match samples \
+            |grep --invert-match grafeas \
+            |grep --invert-match 'cloud-build.*v2' \
+            |grep --invert-match 'google/monitoring/v3/DroppedLabelsOuterClass.java' \
+            |grep --invert-match 'google/cloud/policytroubleshooter/v1/Explanations.java')
+        if [ -n "${invalid_files}" ]; then
+          echo "New invalid package name found. Check the files: ${invalid_files}"
+          exit 1
+        fi
+        echo "No new invalid package names in Java files"
+        
+
