ci: conditional required showcase matrix job

diff --git a/.github/workflows/showcase.yaml b/.github/workflows/showcase.yaml
--- a/.github/workflows/showcase.yaml
+++ b/.github/workflows/showcase.yaml
@@ -216,3 +216,15 @@ jobs:
         run: |
           mvn versions:set -B -ntp -DnewVersion=local
           mvn clirr:check -B -ntp -DcomparisonVersion=$SHOWCASE_CLIENT_VERSION
+
+  required:
+    needs: [ showcase, showcase-java8 ]
+    name: conditional-required-check
+    if: ${{ always() }} # Always run even if any "needs" jobs fail
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Fail if any previous failure
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: exit 1
+      - name: Success otherwise
+        run: echo "Success!"
